[package]
name = "cross-rust-overlay"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl-sys = "*"

[dependencies.sqlx]
version = "0.5.9"
default-features = false
features = [
  "runtime-tokio-rustls",
  "sqlite",
]
