name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: pre-commit-hooks
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build --keep-going
  tests-flakes:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: pre-commit-hooks
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix flake check --show-trace
    - run: nix eval .#lib.x86_64-linux.run --show-trace
