[package]
name = "overlapping-targets"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "*"

[[bin]]
name = "foo"
path = "src/foo.rs"

[[bin]]
name = "bar"
path = "src/foo.rs"

[[bin]]
name = "baz"
path = "src/foo.rs"
