name: Update Nix Inputs

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 * * * *" # every hour

jobs:
  update-inputs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main

      - run: ./updater/update.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "flake.nix resolved-flake.lock README.md deps/"
          commit_message: "Update inputs"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
